### PR TITLE
switch from request to grammy for legacy commands

### PR DESCRIPTION
**Pull request by niteshbalusu11**
Switch from using request to grammy for legacy commands.

notifyOfForwards
postChainTransaction
postClosedMessage
postOpenMessage
postSettledInvoice
postSettledPayment
handleLiquidityCommand

https://github.com/alexbosworth/balanceofsatoshis/issues/176

### CODE REVIEW

**Comment by alexbosworth** [comment]
I tried to fold this in but there is a lot to test and refactor, might have to break it into smaller pieces to be able to do this

**Comment by niteshbalusu11** [comment]
Should I do like 2 commands at a time or something?

**Comment by alexbosworth** [comment]
I think it would be better yeah in smaller pieces so i can do it iteratively, I tried this one and I made it through a bunch but then everything broke and I'm not sure why so I just stashed that and cleaned slate

Also potentially separate the `request` replacement from the `MarkdownV2` replacement aspects

**Comment by niteshbalusu11** [comment]
Cool. I'll do that.

**Comment by niteshbalusu11** [comment]
Will open new PRs, it's git is acting weird when I am trying to undo the last commits.

**Pull request closed without merging**
