### PR TITLE
switch forwards and settled payments to grammy

### PR DESCRIPTION
**Pull request by niteshbalusu11**
Switching notifyOfForwards and postSettledPayment to use grammy over request.

Files changed:
post/notify_of_forwards.js
post/post_settled_payment.js

### CODE REVIEW

**Comment by niteshbalusu11** [comment]
https://github.com/alexbosworth/balanceofsatoshis/issues/176

**Comment by alexbosworth** [comment]
these are cool, my main concern is that we saw some problems with the other changes where send couldn't be a drop in replacement because sendMessage(request) does a fallback to no-markdown which is a second post to telegram

when we dropped it in, it caused a problem where some messages got dropped when there was an error

2 ways to go here:

1. if await send fails, try again without markdown or any formatting
2. convert formatting of messages to use MarkdownV2 and do proper escaping everywhere

**Comment by niteshbalusu11** [comment]
I can convert to MarkdownV2, from what I tested I don't see any errors, but we never know with these formattings.

**Comment by alexbosworth** [comment]
I've seen some forwards posted to my telegram with markdown symbols in them, which means it failed on the first pass

**Comment by niteshbalusu11** [comment]
I added escaping and switched to V2 and it seems to be working ok, the only issue I don't seem to understand is, for some reason, it's notifying a forward twice.

**Comment by alexbosworth** [comment]
I think this will cause test_notify_of_forwards to fail if the strings aren't updated?

**Comment by niteshbalusu11** [comment]
Right, I think the test needs to be updated with escaping and also with the send function replacing request and API args.

**Comment by alexbosworth** [comment]
I replaced the previous tests, it just requires making a dummy send function and then putting `\\` next to the special characters

**Comment by niteshbalusu11** [comment]
Updated the test. `*` need not be escaped btw.

**Comment by niteshbalusu11** [comment]
ok looks like the duplicate forward message issue got fixed as well. No idea how it fixed itself though, maybe `return cbk()` vs `return;` was causing an issue.

**Pull request merged**
