### PR TITLE
added parameters to send amounts in satoshis

### PR DESCRIPTION
**Pull request by bota87**
related to alexbosworth/balanceofsatoshis#219

### CODE REVIEW

**Comment by alexbosworth** [comment]
This involves a lot of argument changes, how about keeping the format tokens abstraction but using an environment variable instead? This way you can check process.env.PREFERRED_TOKENS_TYPE=full or something like that

**Comment by bota87** [comment]
I can try to do that but with an environment variable isn't more complex for users to set that?

**Comment by alexbosworth** [comment]
If you think that's an issue then the flag itself could set the environment variable, you can both get and set process.env.var

**Comment by bota87** [comment]
I followed your advice

**Pull request merged**
