### PR TITLE
Private channel qualifier to pending channels

### PR DESCRIPTION
**Pull request by niteshbalusu11**

### CODE REVIEW

**Comment by alexbosworth** [comment]
Isn't this method already getting is_private when the channel is private? So don't need to get pending again

Seems like most channels are public so that could just be an empty string

Including emoji icons ideally uses the icons.json file

**Comment by alexbosworth** [comment]
There is also a unit test for the open message to adjust for the final output

**Comment by niteshbalusu11** [comment]
> Isn't this method already getting is_private when the channel is private? So don't need to get pending again

I think the subscription doesn't give you is_private. At least from the docs of ln-service

**Comment by alexbosworth** [comment]
hmm maybe the docs are wrong, i'll look into that

**Comment by alexbosworth** [comment]
It is supported yeah because the pending channel subscription itself comes from get pending channels, it's polling

**Comment by niteshbalusu11** [comment]
Cool ok

**Comment by niteshbalusu11** [comment]
Fixed.

**Pull request merged**
