### PR TITLE
used mtokens on rebalance message

### PR DESCRIPTION
**Pull request by bota87**
Same as #10 but for rebalance message

### CODE REVIEW

**Comment by alexbosworth** [comment]
needs update to node test/post/test_get_rebalance_message.js - causes test to fail

**Comment by bota87** [comment]
Right, test fixed

**Comment by alexbosworth** [comment]
ok I also get a failure on test/post/test_post_settled_invoice.js

**Comment by bota87** [comment]
All green!
I had to localize the toRelative function to pass test/commands/test_pending_summary.js

**Pull request merged**
